---
name: "Update kubernetes deployment image"
description: "Update kubernetes deployment image"
inputs:
  kube_config:
    description: "Kube config, regular kubeconfig file enccoded in base64"
    required: true
  namespace:
    description: "Namespace where deployment is located"
    required: true
  name:
    description: "Deployment name"
    required: true
  image:
    description: "Image to be used on update"
    required: true
  container:
    description: "Image to be used on update"
    required: true
  external_secret:
    description: "External secret name"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
